import type { LearnNode } from "@/src/types/learn.types";
import * as LearnIcons from "@/src/icons/tsx/learn";

export const LEARN_NODES: LearnNode[] = [
  {
    id: "wudu",
    title: "Abdest",
    icon: <LearnIcons.WaterDrop width={48} height={60} />,
    href: "/learn/wudu",
    alignment: "left",
    bgColor: "bg-cyan-500",
    bgDark: "bg-cyan-900/50",
    shadowColor: "#083344",
    iconColor: "text-cyan-950",
    variant: "cyan",
    sparkle: {
      icon: <LearnIcons.WaterLux width={20} height={18} />,
      colorClass: "text-cyan-400",
      position: "-top-4 -left-6",
    },
  },
  {
    id: "ghusl",
    title: "Gusül Abdesti",
    icon: <LearnIcons.Shower width={42} height={54} />,
    href: "/learn/ghusl",
    alignment: "right",
    bgColor: "bg-blue-500",
    bgDark: "bg-blue-900/50",
    shadowColor: "#1e3a8a",
    iconColor: "text-blue-950",
    variant: "blue",
  },
  {
    id: "fajr",
    title: "Sabah Namazı",
    icon: <LearnIcons.Sunny width={66} height={66} />,
    href: "/learn/fajr",
    alignment: "center-left",
    bgColor: "bg-amber-500",
    bgDark: "bg-amber-900/50",
    shadowColor: "#451a03",
    iconColor: "text-amber-950",
    variant: "amber",
    innerGradient: "bg-gradient-to-tr from-black/20 to-transparent",
  },
  {
    id: "dhuhr",
    title: "Öğle Namazı",
    icon: <LearnIcons.LightMode width={106} height={106} />,
    href: "/learn/dhuhr",
    alignment: "right",
    bgColor: "bg-yellow-400",
    bgDark: "bg-yellow-900/50",
    shadowColor: "#713f12",
    iconColor: "text-yellow-950",
    variant: "yellow",
  },
  {
    id: "asr",
    title: "İkindi Namazı",
    icon: <LearnIcons.WbSunny width={66} height={66} />,
    href: "/learn/asr",
    alignment: "left",
    bgColor: "bg-orange-500",
    bgDark: "bg-orange-900/50",
    shadowColor: "#7c2d12",
    iconColor: "text-orange-950",
    variant: "orange",
  },
  {
    id: "maghrib",
    title: "Akşam Namazı",
    icon: <LearnIcons.WbTwilight width={60} height={48} />,
    href: "/learn/maghrib",
    alignment: "right",
    bgColor: "bg-rose-600",
    bgDark: "bg-rose-900/50",
    shadowColor: "#4c0519",
    iconColor: "text-rose-950",
    variant: "rose",
    innerGradient: "bg-gradient-to-t from-orange-500/40 to-transparent",
  },
  {
    id: "isha",
    title: "Yatsı Namazı",
    icon: <LearnIcons.Bedtime width={60} height={60} />,
    href: "/learn/isha",
    alignment: "center",
    bgColor: "bg-indigo-700",
    bgDark: "bg-indigo-900/50",
    shadowColor: "#1e1b4b",
    iconColor: "text-indigo-100",
    variant: "indigo",
    sparkle: {
      icon: <LearnIcons.Star width={20} height={19} />,
      colorClass: "text-indigo-300",
      position: "-top-8 -right-4",
    },
  },
  {
    id: "jumuah",
    title: "Cuma Namazı",
    icon: <LearnIcons.Mosque width={160} height={140} />,
    href: "/learn/jumuah",
    alignment: "center",
    bgColor: "bg-emerald-600",
    bgDark: "bg-emerald-900/50",
    shadowColor: "#022c22",
    iconColor: "text-emerald-50",
    variant: "emerald",
    innerGradient: "bg-gradient-to-tr from-green-800/30 to-transparent",
    isFeatured: true,
  },
] as const;
