import { PrayerKey, Madhab } from "../types/enums/worship.enums";
import type { City } from "../types/worship.types";

interface PrayerConfig {
  key: PrayerKey;
  label: string;
  shortLabel: string;
  iconName: PrayerIconName;
  color: string;
  shadow: string;
  order: number;
}

type PrayerIconName = "fajr" | "sunrise" | "dhuhr" | "asr" | "maghrib" | "isha";

export const PRAYER_ORDER: readonly PrayerKey[] = [
  PrayerKey.Fajr,
  PrayerKey.Sunrise,
  PrayerKey.Dhuhr,
  PrayerKey.Asr,
  PrayerKey.Maghrib,
  PrayerKey.Isha,
] as const;

export const PRAYER_CONFIG: Record<PrayerKey, PrayerConfig> = {
  [PrayerKey.Fajr]: {
    key: PrayerKey.Fajr,
    label: "İmsak",
    shortLabel: "İmsak",
    iconName: "fajr",
    color: "#F59E0B",
    shadow: "#7C4509",
    order: 0,
  },
  [PrayerKey.Sunrise]: {
    key: PrayerKey.Sunrise,
    label: "Güneş",
    shortLabel: "Güneş",
    iconName: "sunrise",
    color: "#FACC15",
    shadow: "#7E5C12",
    order: 1,
  },
  [PrayerKey.Dhuhr]: {
    key: PrayerKey.Dhuhr,
    label: "Öğle",
    shortLabel: "Öğle",
    iconName: "dhuhr",
    color: "#F97316",
    shadow: "#7E3A0F",
    order: 2,
  },
  [PrayerKey.Asr]: {
    key: PrayerKey.Asr,
    label: "İkindi",
    shortLabel: "İkindi",
    iconName: "asr",
    color: "#FB923C",
    shadow: "#7E2D0E",
    order: 3,
  },
  [PrayerKey.Maghrib]: {
    key: PrayerKey.Maghrib,
    label: "Akşam",
    shortLabel: "Akşam",
    iconName: "maghrib",
    color: "#E11D48",
    shadow: "#7B0E2A",
    order: 4,
  },
  [PrayerKey.Isha]: {
    key: PrayerKey.Isha,
    label: "Yatsı",
    shortLabel: "Yatsı",
    iconName: "isha",
    color: "#6366F1",
    shadow: "#2D2C7E",
    order: 5,
  },
};

export const PRAYER_STATE_LABEL: Record<string, string> = {
  passed: "Geçti",
  current: "Şu an",
  upcoming: "Bekliyor",
};

export const MONTHS_TR: readonly string[] = [
  "Ocak",
  "Şubat",
  "Mart",
  "Nisan",
  "Mayıs",
  "Haziran",
  "Temmuz",
  "Ağustos",
  "Eylül",
  "Ekim",
  "Kasım",
  "Aralık",
] as const;

export const DAYS_LONG_TR: readonly string[] = [
  "Pazar",
  "Pazartesi",
  "Salı",
  "Çarşamba",
  "Perşembe",
  "Cuma",
  "Cumartesi",
] as const;

export const DEFAULT_CITY: City = {
  id: "istanbul",
  name: "İstanbul",
  lat: 41.0082,
  lng: 28.9784,
  timezone: "Europe/Istanbul",
};

export const TURKISH_CITIES: readonly City[] = [
  {
    id: "adana",
    name: "Adana",
    lat: 37.0,
    lng: 35.3213,
    timezone: "Europe/Istanbul",
  },
  {
    id: "adiyaman",
    name: "Adıyaman",
    lat: 37.7648,
    lng: 38.2786,
    timezone: "Europe/Istanbul",
  },
  {
    id: "afyonkarahisar",
    name: "Afyonkarahisar",
    lat: 38.7569,
    lng: 30.5387,
    timezone: "Europe/Istanbul",
  },
  {
    id: "agri",
    name: "Ağrı",
    lat: 39.7191,
    lng: 43.0503,
    timezone: "Europe/Istanbul",
  },
  {
    id: "aksaray",
    name: "Aksaray",
    lat: 38.3687,
    lng: 34.037,
    timezone: "Europe/Istanbul",
  },
  {
    id: "amasya",
    name: "Amasya",
    lat: 40.6499,
    lng: 35.8353,
    timezone: "Europe/Istanbul",
  },
  {
    id: "ankara",
    name: "Ankara",
    lat: 39.9334,
    lng: 32.8597,
    timezone: "Europe/Istanbul",
  },
  {
    id: "antalya",
    name: "Antalya",
    lat: 36.8969,
    lng: 30.7133,
    timezone: "Europe/Istanbul",
  },
  {
    id: "ardahan",
    name: "Ardahan",
    lat: 41.1105,
    lng: 42.7022,
    timezone: "Europe/Istanbul",
  },
  {
    id: "artvin",
    name: "Artvin",
    lat: 41.1828,
    lng: 41.8183,
    timezone: "Europe/Istanbul",
  },
  {
    id: "aydin",
    name: "Aydın",
    lat: 37.856,
    lng: 27.8416,
    timezone: "Europe/Istanbul",
  },
  {
    id: "balikesir",
    name: "Balıkesir",
    lat: 39.6484,
    lng: 27.8826,
    timezone: "Europe/Istanbul",
  },
  {
    id: "bartin",
    name: "Bartın",
    lat: 41.6344,
    lng: 32.3375,
    timezone: "Europe/Istanbul",
  },
  {
    id: "batman",
    name: "Batman",
    lat: 37.8812,
    lng: 41.1351,
    timezone: "Europe/Istanbul",
  },
  {
    id: "bayburt",
    name: "Bayburt",
    lat: 40.2552,
    lng: 40.2249,
    timezone: "Europe/Istanbul",
  },
  {
    id: "bilecik",
    name: "Bilecik",
    lat: 40.1506,
    lng: 29.9833,
    timezone: "Europe/Istanbul",
  },
  {
    id: "bingol",
    name: "Bingöl",
    lat: 38.8854,
    lng: 40.4983,
    timezone: "Europe/Istanbul",
  },
  {
    id: "bitlis",
    name: "Bitlis",
    lat: 38.4006,
    lng: 42.1095,
    timezone: "Europe/Istanbul",
  },
  {
    id: "bolu",
    name: "Bolu",
    lat: 40.7395,
    lng: 31.6116,
    timezone: "Europe/Istanbul",
  },
  {
    id: "burdur",
    name: "Burdur",
    lat: 37.7203,
    lng: 30.2908,
    timezone: "Europe/Istanbul",
  },
  {
    id: "bursa",
    name: "Bursa",
    lat: 40.1828,
    lng: 29.067,
    timezone: "Europe/Istanbul",
  },
  {
    id: "canakkale",
    name: "Çanakkale",
    lat: 40.1553,
    lng: 26.4142,
    timezone: "Europe/Istanbul",
  },
  {
    id: "cankiri",
    name: "Çankırı",
    lat: 40.6013,
    lng: 33.6134,
    timezone: "Europe/Istanbul",
  },
  {
    id: "corum",
    name: "Çorum",
    lat: 40.5506,
    lng: 34.9556,
    timezone: "Europe/Istanbul",
  },
  {
    id: "denizli",
    name: "Denizli",
    lat: 37.7765,
    lng: 29.0864,
    timezone: "Europe/Istanbul",
  },
  {
    id: "diyarbakir",
    name: "Diyarbakır",
    lat: 37.9144,
    lng: 40.2306,
    timezone: "Europe/Istanbul",
  },
  {
    id: "duzce",
    name: "Düzce",
    lat: 40.8438,
    lng: 31.1565,
    timezone: "Europe/Istanbul",
  },
  {
    id: "edirne",
    name: "Edirne",
    lat: 41.6772,
    lng: 26.5557,
    timezone: "Europe/Istanbul",
  },
  {
    id: "elazig",
    name: "Elazığ",
    lat: 38.6748,
    lng: 39.2232,
    timezone: "Europe/Istanbul",
  },
  {
    id: "erzincan",
    name: "Erzincan",
    lat: 39.75,
    lng: 39.5,
    timezone: "Europe/Istanbul",
  },
  {
    id: "erzurum",
    name: "Erzurum",
    lat: 39.9,
    lng: 41.27,
    timezone: "Europe/Istanbul",
  },
  {
    id: "eskisehir",
    name: "Eskişehir",
    lat: 39.7767,
    lng: 30.5206,
    timezone: "Europe/Istanbul",
  },
  {
    id: "gaziantep",
    name: "Gaziantep",
    lat: 37.0662,
    lng: 37.3833,
    timezone: "Europe/Istanbul",
  },
  {
    id: "giresun",
    name: "Giresun",
    lat: 40.9128,
    lng: 38.3895,
    timezone: "Europe/Istanbul",
  },
  {
    id: "gumushane",
    name: "Gümüşhane",
    lat: 40.4603,
    lng: 39.4814,
    timezone: "Europe/Istanbul",
  },
  {
    id: "hakkari",
    name: "Hakkâri",
    lat: 37.5744,
    lng: 43.7408,
    timezone: "Europe/Istanbul",
  },
  {
    id: "hatay",
    name: "Hatay",
    lat: 36.2021,
    lng: 36.1606,
    timezone: "Europe/Istanbul",
  },
  {
    id: "igdir",
    name: "Iğdır",
    lat: 39.9237,
    lng: 44.045,
    timezone: "Europe/Istanbul",
  },
  {
    id: "isparta",
    name: "Isparta",
    lat: 37.7648,
    lng: 30.5566,
    timezone: "Europe/Istanbul",
  },
  {
    id: "istanbul",
    name: "İstanbul",
    lat: 41.0082,
    lng: 28.9784,
    timezone: "Europe/Istanbul",
  },
  {
    id: "izmir",
    name: "İzmir",
    lat: 38.4192,
    lng: 27.1287,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kahramanmaras",
    name: "Kahramanmaraş",
    lat: 37.5736,
    lng: 36.9371,
    timezone: "Europe/Istanbul",
  },
  {
    id: "karabuk",
    name: "Karabük",
    lat: 41.2061,
    lng: 32.6204,
    timezone: "Europe/Istanbul",
  },
  {
    id: "karaman",
    name: "Karaman",
    lat: 37.1811,
    lng: 33.215,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kars",
    name: "Kars",
    lat: 40.6013,
    lng: 43.0975,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kastamonu",
    name: "Kastamonu",
    lat: 41.3887,
    lng: 33.7827,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kayseri",
    name: "Kayseri",
    lat: 38.7312,
    lng: 35.4787,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kirikkale",
    name: "Kırıkkale",
    lat: 39.8468,
    lng: 33.5153,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kirklareli",
    name: "Kırklareli",
    lat: 41.7333,
    lng: 27.2167,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kirsehir",
    name: "Kırşehir",
    lat: 39.1458,
    lng: 34.1606,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kilis",
    name: "Kilis",
    lat: 36.7184,
    lng: 37.1212,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kocaeli",
    name: "Kocaeli",
    lat: 40.7654,
    lng: 29.9408,
    timezone: "Europe/Istanbul",
  },
  {
    id: "konya",
    name: "Konya",
    lat: 37.8746,
    lng: 32.4932,
    timezone: "Europe/Istanbul",
  },
  {
    id: "kutahya",
    name: "Kütahya",
    lat: 39.4242,
    lng: 29.9833,
    timezone: "Europe/Istanbul",
  },
  {
    id: "malatya",
    name: "Malatya",
    lat: 38.3554,
    lng: 38.3335,
    timezone: "Europe/Istanbul",
  },
  {
    id: "manisa",
    name: "Manisa",
    lat: 38.6191,
    lng: 27.4289,
    timezone: "Europe/Istanbul",
  },
  {
    id: "mardin",
    name: "Mardin",
    lat: 37.3212,
    lng: 40.7245,
    timezone: "Europe/Istanbul",
  },
  {
    id: "mersin",
    name: "Mersin",
    lat: 36.8121,
    lng: 34.6415,
    timezone: "Europe/Istanbul",
  },
  {
    id: "mugla",
    name: "Muğla",
    lat: 37.2153,
    lng: 28.3636,
    timezone: "Europe/Istanbul",
  },
  {
    id: "mus",
    name: "Muş",
    lat: 38.9462,
    lng: 41.7539,
    timezone: "Europe/Istanbul",
  },
  {
    id: "nevsehir",
    name: "Nevşehir",
    lat: 38.6244,
    lng: 34.7141,
    timezone: "Europe/Istanbul",
  },
  {
    id: "nigde",
    name: "Niğde",
    lat: 37.9698,
    lng: 34.6766,
    timezone: "Europe/Istanbul",
  },
  {
    id: "ordu",
    name: "Ordu",
    lat: 40.9862,
    lng: 37.8797,
    timezone: "Europe/Istanbul",
  },
  {
    id: "osmaniye",
    name: "Osmaniye",
    lat: 37.0742,
    lng: 36.2478,
    timezone: "Europe/Istanbul",
  },
  {
    id: "rize",
    name: "Rize",
    lat: 41.0201,
    lng: 40.5234,
    timezone: "Europe/Istanbul",
  },
  {
    id: "sakarya",
    name: "Sakarya",
    lat: 40.7569,
    lng: 30.3781,
    timezone: "Europe/Istanbul",
  },
  {
    id: "samsun",
    name: "Samsun",
    lat: 41.2867,
    lng: 36.33,
    timezone: "Europe/Istanbul",
  },
  {
    id: "siirt",
    name: "Siirt",
    lat: 37.9333,
    lng: 41.95,
    timezone: "Europe/Istanbul",
  },
  {
    id: "sinop",
    name: "Sinop",
    lat: 42.0231,
    lng: 35.1531,
    timezone: "Europe/Istanbul",
  },
  {
    id: "sirnak",
    name: "Şırnak",
    lat: 37.5164,
    lng: 42.4611,
    timezone: "Europe/Istanbul",
  },
  {
    id: "sivas",
    name: "Sivas",
    lat: 39.7477,
    lng: 37.0179,
    timezone: "Europe/Istanbul",
  },
  {
    id: "sanliurfa",
    name: "Şanlıurfa",
    lat: 37.1591,
    lng: 38.7969,
    timezone: "Europe/Istanbul",
  },
  {
    id: "tekirdag",
    name: "Tekirdağ",
    lat: 40.9833,
    lng: 27.5167,
    timezone: "Europe/Istanbul",
  },
  {
    id: "tokat",
    name: "Tokat",
    lat: 40.3167,
    lng: 36.55,
    timezone: "Europe/Istanbul",
  },
  {
    id: "trabzon",
    name: "Trabzon",
    lat: 41.0027,
    lng: 39.7168,
    timezone: "Europe/Istanbul",
  },
  {
    id: "tunceli",
    name: "Tunceli",
    lat: 39.1081,
    lng: 39.5471,
    timezone: "Europe/Istanbul",
  },
  {
    id: "usak",
    name: "Uşak",
    lat: 38.6823,
    lng: 29.4082,
    timezone: "Europe/Istanbul",
  },
  {
    id: "van",
    name: "Van",
    lat: 38.4942,
    lng: 43.38,
    timezone: "Europe/Istanbul",
  },
  {
    id: "yalova",
    name: "Yalova",
    lat: 40.655,
    lng: 29.2769,
    timezone: "Europe/Istanbul",
  },
  {
    id: "yozgat",
    name: "Yozgat",
    lat: 39.8181,
    lng: 34.8147,
    timezone: "Europe/Istanbul",
  },
  {
    id: "zonguldak",
    name: "Zonguldak",
    lat: 41.4564,
    lng: 31.7987,
    timezone: "Europe/Istanbul",
  },
] as const;

export const MADHAB_LABEL: Record<string, string> = {
  [Madhab.Shafi]: "Şâfiî",
  [Madhab.Hanafi]: "Hanefî",
};

export const WORSHIP_QUERY_KEYS = {
  all: ["worship"] as const,
  times: (params: { date: string }) => ["worship", "times", params] as const,
  options: () => ["worship", "options"] as const,
};

export const WORSHIP_STALE_TIME = 60 * 1000;
export const WORSHIP_OPTIONS_STALE_TIME = 60 * 60 * 1000;
export const WORSHIP_REFRESH_INTERVAL = 5 * 60 * 1000;
export const COUNTDOWN_TICK_MS = 1000;
export const DAY_CHANGE_CHECK_MS = 30 * 1000;

export const COORDINATE_PRECISION = 4;
export const ARC_RADIUS = 84;
export const ARC_WIDTH = 620;
export const ARC_HEIGHT = 200;
