export enum ConsentErrorCode {
  TERMS_NOT_ACCEPTED = "TERMS_NOT_ACCEPTED",
  PRIVACY_POLICY_NOT_ACCEPTED = "PRIVACY_POLICY_NOT_ACCEPTED",
  CONSENT_REQUIRED = "CONSENT_REQUIRED",
  CONSENT_OUTDATED = "CONSENT_OUTDATED",
}
